services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 20084:443
    restart: always
  react:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
  rosflask:
    build:
      context: ./rosflask
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    tty: true 