services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
      - 80:80
    restart: always
  react:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
  rosflask:
    build:
      context: ./rosflask
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    tty: true 
